import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="h-full">
      <Head>
        <title>Nathapon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        <div className="max-w-screen-sm mx-auto w-full">
          <h1 className="text-6xl text-center mt-20">Nathapon</h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div>
            <h1 className="text-3xl">Nathapon Boonthawngkaew</h1>
            <p className="text-lg">Web / Mobile Developer, Pixel Artist</p>
            <div className="mt-5">
              <p className="font-bold underline">Bio</p>
              <p>1996 Born in Nakhon Sri thammarat, Thailand</p>
              <p>
                2020 Completed Bechelor Degree in Humanities at MCU Buddhist
                University, Ayuddhaya
              </p>
              <p>
                2022-Present Work at Junior Web developer at Kratos tracking,
                Bangkok
              </p>
              <p>
                I am a kind of person who found coding is fun not just a career
                to earning, Everything related to Computer Sciences, technology,
                Space i love it
              </p>
            </div>
            <div className="mt-5">
              <p className="font-bold underline">Work</p>
              <p>
                Takuya is a freelance and a full-stack developer based in Osaka
                with a passion for building digital services/stuff he wants. He
                has a knack for all things launching products, from planning and
                designing all the way to solving real-life problems with code.
                When not online, he loves hanging out with his camera.
                Currently, he is living off of his own product called Inkdrop.
                He publishes content for marketing his products and his YouTube
                channel called "Dev as Life" has more than 100k subscribers.
              </p>
            </div>

            <div className="mt-5">
              <p className="font-bold underline">Skills</p>
              <p>Programming Languages: Typescript, Go, Dart, Python</p>
              <p>Fields: Web development, Mobile development, Data analysis,</p>
            </div>
            <div className="mt-5">
              <p className="font-bold underline">Contact</p>
              <p>Line: </p>
              <p>Email: hellonathapon@gmail.com</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
